# ``conda env create --file environment.yml``
# or
# ``conda env create --name <myEnvName> --file environment.yml``

name: cgihowfs
dependencies:
  - numpy
  - scipy
  - astropy
  - conda-forge::pyyaml
  - conda-forge::joblib
  - python>=3.9
  - pip
  - pip:
    - git+https://github.com/nasa-jpl/cgi-eetc.git@v3.0.0